version: "3.7"

services:
  postgres:
    image: postgres:12-alpine
    env_file: .env
    environment:
      PGDATA: /var/lib/postgresql/data/rankr/
      POSTGRES_DB: ${POSTGRESQL_NAME}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    healthcheck:
      test: wget -nv -t 3 -T 10 --spider ${HEALTHCHECKS_POSTGRES}
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - traefik-public-network
    ports:
      - ${POSTGRESQL_PORT}:${POSTGRESQL_PORT}
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data/

  adminer:
    image: michalhosna/adminer:latest
    env_file: .env
    command: php -S ${ADMINER_HOST}:${ADMINER_PORT} -t /var/adminer
    depends_on:
      - postgres
    healthcheck:
      test: wget -nv -t 3 -T 10 --spider ${HEALTHCHECKS_ADMINER}
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    init: true
    labels:
      - traefik.enable=true

      - traefik.http.middlewares.${STACK_NAME}-adminer-https-redirect.redirectscheme.permanent=true
      - traefik.http.middlewares.${STACK_NAME}-adminer-https-redirect.redirectscheme.scheme=https

      - traefik.http.routers.${STACK_NAME}-adminer-http.entrypoints=http
      - traefik.http.routers.${STACK_NAME}-adminer-http.middlewares=${STACK_NAME}-adminer-https-redirect
      - traefik.http.routers.${STACK_NAME}-adminer-http.rule=HOST(`adminer.${DOMAIN}`)

      - traefik.http.routers.${STACK_NAME}-adminer-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME}-adminer-https.rule=HOST(`adminer.${DOMAIN}`)
      - traefik.http.routers.${STACK_NAME}-adminer-https.tls=true
      - traefik.http.routers.${STACK_NAME}-adminer-https.tls.certresolver=le

      - traefik.http.services.${STACK_NAME}-adminer.loadbalancer.server.port=${ADMINER_PORT}
    networks:
      - traefik-public-network
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}
    restart: always

  redis:
    image: redis:6.2.5-alpine
    env_file: .env
    command: redis-server --requirepass ${REDIS_PASS}
    networks:
      - traefik-public-network
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    sysctls:
      net.core.somaxconn: 511
    restart: always
    volumes:
      - redis:/var/lib/redis/data

  backend:
    build:
      args:
        INSTALL_PATH: ${INSTALL_PATH}
        POETRY_VERSION: ${POETRY_VERSION}
      context: ./backend
      dockerfile: backend.dockerfile
    command: sh -c 'rankr start'
    depends_on:
      - postgres
    env_file: .env
    healthcheck:
      test: wget -nv -t 3 -T 10 --spider ${HEALTHCHECKS_BACKEND}
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - traefik.enable=true

      - traefik.http.middlewares.${STACK_NAME}-backend-https-redirect.redirectscheme.permanent=true
      - traefik.http.middlewares.${STACK_NAME}-backend-https-redirect.redirectscheme.scheme=https

      - traefik.http.routers.${STACK_NAME}-backend-http.entrypoints=http
      - traefik.http.routers.${STACK_NAME}-backend-http.middlewares=${STACK_NAME}-backend-https-redirect
      - traefik.http.routers.${STACK_NAME}-backend-http.rule=HOST(`${DOMAIN}`) && PathPrefix(`${API_V1_STR}`)

      - traefik.http.routers.${STACK_NAME}-backend-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME}-backend-https.rule=HOST(`${DOMAIN}`) && PathPrefix(`${API_V1_STR}`)
      - traefik.http.routers.${STACK_NAME}-backend-https.tls=true
      - traefik.http.routers.${STACK_NAME}-backend-https.tls.certresolver=le

      - traefik.http.middlewares.${STACK_NAME}-backend-ratelimit.ratelimit.average=8
      - traefik.http.middlewares.${STACK_NAME}-backend-ratelimit.ratelimit.burst=8
      - traefik.http.middlewares.${STACK_NAME}-backend-ratelimit.ratelimit.period=1

      - traefik.http.services.${STACK_NAME}-backend.loadbalancer.server.port=${BACKEND_PORT}
    networks:
      - traefik-public-network
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    restart: always
    volumes:
      - ./backend/data:${INSTALL_PATH}/data

  frontend:
    build:
      args:
        INSTALL_PATH: ${INSTALL_PATH}
        REACT_APP_API_V1_STR: ${REACT_APP_API_V1_STR}
        REACT_APP_DEV_BACKEND_HOST: ${REACT_APP_DEV_BACKEND_HOST}
        REACT_APP_DEV_BACKEND_PORT: ${REACT_APP_DEV_BACKEND_PORT}
        REACT_APP_FRONTEND_ENV: ${REACT_APP_FRONTEND_ENV}
        REACT_APP_FRONTEND_NAME: ${REACT_APP_FRONTEND_NAME}
        REACT_APP_FRONTEND_URL: ${REACT_APP_FRONTEND_URL}
        REACT_APP_PROD_BACKEND_URL: ${REACT_APP_PROD_BACKEND_URL}
      context: ./frontend
      dockerfile: frontend.dockerfile
    depends_on:
      - backend
    env_file: .env
    labels:
      - traefik.enable=true

      - traefik.http.middlewares.${STACK_NAME}-frontend-https-redirect.redirectscheme.permanent=true
      - traefik.http.middlewares.${STACK_NAME}-frontend-https-redirect.redirectscheme.scheme=https

      - traefik.http.routers.${STACK_NAME}-frontend-http.entrypoints=http
      - traefik.http.routers.${STACK_NAME}-frontend-http.middlewares=${STACK_NAME}-frontend-https-redirect
      - traefik.http.routers.${STACK_NAME}-frontend-http.rule=HOST(`${DOMAIN}`) && PathPrefix(`/`)

      - traefik.http.routers.${STACK_NAME}-frontend-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME}-frontend-https.rule=HOST(`${DOMAIN}`) && PathPrefix(`/`)
      - traefik.http.routers.${STACK_NAME}-frontend-https.tls=true
      - traefik.http.routers.${STACK_NAME}-frontend-https.tls.certresolver=le

      - traefik.http.services.${STACK_NAME}-frontend.loadbalancer.server.port=80
    networks:
      - traefik-public-network
    restart: always

  traefik:
    image: traefik:v2.9
    command:
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.docker
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
      # Create an entrypoint 'http' listening on port '80'
      - --entrypoints.http.address=:80
      # Create an entrypoint 'https' listening on port '443'
      - --entrypoints.https.address=:443
      # Create the certificate resolver 'le' for Let's Encrypt
      - --certificatesresolvers.le.acme.email=${LETS_ENCRYPT_EMAIL}
      # Store the certificate in the mounted volume
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      # Use the TLS challenge
      - --certificatesresolvers.le.acme.tlschallenge=true

      # Enable the access log, with HTTP requests
      - --accesslog
      - --accesslog.bufferingsize=100
      # Enable the Traefik log, for configurations and errors
      - --log
      - --log.format=json
      # Enable the Dashboard and API
      - --api
    env_file: .env
    healthcheck:
      test: wget -nv -t 3 -T 10 --spider ${HEALTHCHECKS_TRAEFIK}
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - traefik.enable=true

      - traefik.http.middlewares.${STACK_NAME}-traefik-https-redirect.redirectscheme.permanent=true
      - traefik.http.middlewares.${STACK_NAME}-traefik-https-redirect.redirectscheme.scheme=https

      - traefik.http.routers.${STACK_NAME}-traefik-http.entrypoints=http
      - traefik.http.routers.${STACK_NAME}-traefik-http.middlewares=${STACK_NAME}-traefik-https-redirect
      - traefik.http.routers.${STACK_NAME}-traefik-http.rule=Host(`traefik.${DOMAIN}`)

      - traefik.http.routers.${STACK_NAME}-traefik-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME}-traefik-https.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.${STACK_NAME}-traefik-https.service=api@internal
      - traefik.http.routers.${STACK_NAME}-traefik-https.tls=true
      - traefik.http.routers.${STACK_NAME}-traefik-https.tls.certresolver=le

      - traefik.http.services.${STACK_NAME}-traefik.loadbalancer.server.port=${TRAEFIK_PORT}
    networks:
      - traefik-public-network
    ports:
      - 80:80
      - 443:443
      - ${TRAEFIK_PORT}:${TRAEFIK_PORT}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-public-certificates:/certificates

networks:
  traefik-public-network:
    external: true

volumes:
  postgres:
  redis:
  traefik-public-certificates:
